version: "3"

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: srushtii13/backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - CONNECTION_URL=mongodb://mongo:27017/stackoverflow
      - PORT=8080
    depends_on:
      - mongo

  frontend:
    image: srushtii13/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
